# Step 01: Regression

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings as wr
wr.filterwarnings('ignore')
df1 = pd.read_csv('weight-height.csv')
df1.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [87]:
df2 = df1.copy()
df3 = df1.copy()
df4 = df1.copy()

2. Separate x(Gender, Height) and y (y=Weight)
3. Train = 70%, Test = 30%
4. Apply Linear Regression
5. Evaluate the Model (Testing and training Accuracy, MSE for testing)
6. Apply KNN Regressor: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html
7. Evaluate the Model (Testing and training Accuracy, MSE for testing)
8. Compare KNN & Linear regression with the KNN model and Linear regression as well.


Work from here..

In [24]:
y= df1[['Weight']]
y.head()

Weight
0  241.893563
1  162.310473
2  212.740856
3  220.042470
4  206.349801

In [25]:
x = df1.drop('Weight' , axis =1)
x

Gender     Height
0       Male  73.847017
1       Male  68.781904
2       Male  74.110105
3       Male  71.730978
4       Male  69.881796
...      ...        ...
8550  Female  60.483946
8551  Female  63.423372
8552  Female  65.584057
8553  Female  67.429971
8554  Female  60.921791

[8555 rows x 2 columns]

In [26]:
x.Gender.nunique()

2

In [27]:
x.Gender.value_counts()

Male      5000
Female    3555
Name: Gender, dtype: int64

In [32]:
df3[['Gender']]

Gender
0       Male
1       Male
2       Male
3       Male
4       Male
...      ...
8550  Female
8551  Female
8552  Female
8553  Female
8554  Female

[8555 rows x 1 columns]

In [36]:
df3.Gender = df3.Gender.replace(['Male', 'Female'], [1,2]) 
df3[['Gender']].head()


Gender
0       1
1       1
2       1
3       1
4       1

In [43]:
x =pd.concat([x.Height,df3.Gender] , axis =1)

In [46]:
x.head(100)

Height  Gender
0   73.847017       1
1   68.781904       1
2   74.110105       1
3   71.730978       1
4   69.881796       1
..        ...     ...
95  65.117485       1
96  71.701234       1
97  66.832878       1
98  66.471275       1
99  69.411526       1

[100 rows x 2 columns]

In [47]:
from sklearn.model_selection import train_test_split  as tts

In [48]:
xtrain , xtest ,ytrain , ytest = tts(x,y,test_size = .30 ,random_state = 1  )

In [51]:
xtrain.head()

Height  Gender
1277  72.385301       1
5361  60.960147       2
5728  69.119292       2
4276  68.271050       1
3112  64.991405       1

In [52]:
xtest.head()

Height  Gender
7154  65.068038       2
3258  70.824643       1
2188  68.663594       1
5609  65.987610       2
3186  70.901461       1

In [53]:
x.head()

Height  Gender
0  73.847017       1
1  68.781904       1
2  74.110105       1
3  71.730978       1
4  69.881796       1

In [54]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg

LinearRegression()

In [55]:
reg.fit(xtrain,ytrain)

LinearRegression()

In [57]:
reg.coef_

array([[  5.96887438, -19.34359322]])

In [58]:
reg.intercept_

array([-205.86562259])

In [59]:
 y = 5.9688*73.847017 -19.3435*1 + -205.86

In [60]:
y

215.57457506959992

In [62]:
reg.predict([[73.847017 , 1]])

array([[215.5743523]])

In [66]:
from sklearn.metrics import mean_squared_error

In [67]:
test_mse = mean_squared_error(ytest , reg.predict(xtest))

In [68]:
test_mse

99.67250998070031

# knn method

In [72]:
from sklearn.neighbors import KNeighborsRegressor

In [77]:
neigh = KNeighborsRegressor(n_neighbors=2)

In [78]:
neigh.fit(xtest,ytest)

KNeighborsRegressor(n_neighbors=2)

In [80]:
neigh.predict([[73.847017 , 1]])

array([[216.87727415]])

# accuricy

In [81]:
reg.score(xtest ,ytest)

0.905995960709116

In [82]:
reg.score(xtrain, ytrain)

0.8972135459668118

# Step 02: Classification

In [88]:
df4.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

2. Separate x and (y=Gender)
3. Train = 70%, Test = 30%
4. Apply KNN Classifier 
5. Evaluate the Model by only Accuracy.
6. Apply KNN Classifier: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

Work from here..

In [89]:
y= df4[['Gender']]
y.head()

Gender
0   Male
1   Male
2   Male
3   Male
4   Male

In [91]:
x = df4.drop('Gender' , axis =1)
x.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [92]:
from sklearn.model_selection import train_test_split  as tts

In [93]:
xtrain , xtest ,ytrain , ytest = tts(x,y,test_size = .30 ,random_state = 1  )

In [96]:
xtest.head()

Height      Weight
7154  65.068038  160.800726
3258  70.824643  184.516688
2188  68.663594  184.262796
5609  65.987610  166.844114
3186  70.901461  200.466282

In [97]:
ytest.head()

Gender
7154  Female
3258    Male
2188    Male
5609  Female
3186    Male

In [98]:
xtrain.head()

Height      Weight
1277  72.385301  189.165592
5361  60.960147  124.876796
5728  69.119292  168.864403
4276  68.271050  172.941248
3112  64.991405  144.551044

In [99]:
ytrain.head()

Gender
1277    Male
5361  Female
5728  Female
4276    Male
3112    Male

In [100]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)

In [101]:
neigh.fit(xtrain, ytrain)

KNeighborsClassifier(n_neighbors=3)

In [102]:
neigh.predict([[72.385301, 189.165592]])

array(['Male'], dtype=object)